---

language: python
python:
- "2.7"
- "3.5"
install:
- pip install -e .[test]
script:
- nosetests --with-doctest --with-coverage --cover-package=tabular --cover-min-percentage=11
sudo: false
git:
  depth: 250